import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head"; // Import Head for additional metadata

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Inventory Pro",
  description: "Generated by Inventory Pro",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Add any additional meta tags or links here */}
      </Head>
      <body className={inter.className}>
        {/* Global layout components like Header or Sidebar can go here */}
        {children}
        {/* Global layout components like Footer can go here */}
      </body>
    </html>
  );
}
